Prefer empty line after an opening brace and beginning of closure. Al…
metova/swift-style-guide pull request #5
Opened 2017-03-28 16:24 UTC by drewpitchford

@lgauthier see what you think of these. I think they are good additions. I'm adding cause I intend on getting my team at mSignia to follow this style guide.

2017-03-28 17:28 UTC, drewpitchford commented
adding @skyem to this PR too

2017-03-28 17:36 UTC, lgauthier commented
@drewpitchford What's the rationale for the empty line after all opening braces? Personally, I think it would contribute to some unnecessary whitespace that could decrease readability because it would make the use of whitespace more homogeneous throughout the codebase rather than focussed on grouping related code. Either way, if we're going to add it, we'd want to add a rationale after the rule like we do with the other rules.

2017-03-28 17:36 UTC, lgauthier commented
@nhgrif Thoughts?

2017-03-28 17:50 UTC, drewpitchford commented
@lgauthier I added a rationale. I believe it helps readability by separating the signature from the definition thus making it easier to pick up the beginning of the definition quickly.

2017-03-29 16:19 UTC, drewpitchford commented
Any further comments? Or final yay/nay? I did add a section about property declarations too as I'm seeing that is not universally understood either.

2017-03-30 15:26 UTC, lgauthier commented
@drewpitchford Sorry for the delay. I've been a little swamped the past couple days. I personally don't like the blank line after opening braces rule, but I'd like to hear what others think. Overall, if there are mixed feelings about it, I'd prefer to make no rule about it so people are free to do it how they prefer. I'd be more open to having a rule stating to always have a blank line after opening braces for function definitions or type definitions, but I like to be able to choose whether to include one or not for control statements and stuff depending on what I think makes it more readable.

I still need to review the other changes proposed here, so I'll get back to you on those hopefully sometime today.

2017-03-30 15:36 UTC, lgauthier commented
@drewpitchford Just looked at the property declarations rule. I completely agree that we should have that in there, but I think we can make it even more generic because that's a colon spacing rule that should really apply in many other cases as well. I like this rule from [Ray Wenderlich's style guide](https://github.com/raywenderlich/swift-style-guide):

> Colons always have no space on the left and one space on the right. Exceptions are the ternary operator ? :, empty dictionary [:] and #selector syntax for unnamed parameters (_:).

2017-03-30 15:36 UTC, lgauthier commented
Also, we should probably separate these different rule proposals into different PRs.

2017-03-30 15:40 UTC, drewpitchford commented
Ok, I'm not sure how to separate them out of this PR other than undoing the work.

2017-03-30 15:44 UTC, lgauthier commented
@nhgrif @Truked @BevTheDev You guys should probably weigh in as well before we change anything.

2017-04-17 19:15 UTC, nhgrif requested changes
In addition to the comments I've left, I agree with @lgauthier that we should put each section you're adding in its own PR.

2017-04-17 19:15 UTC, nhgrif commented on README.md
> +myMethod() {
I believe elsewhere in the style guide, we specify these parentheses should be omitted, so we should fix that.  (If we don't specify it, we should...)  We can just add an argument inside the parenthesis.

2017-04-17 19:15 UTC, nhgrif commented on README.md
> +##### Use dot syntax on enums and static vars where type can be inferred.
Is "static vars" the right phrase for this?  Should these be "static properties"?  And is dropping the type specification referred to as "dot syntax"?  I'm curious if there's a more accurate name for this shortening.

2017-04-17 19:16 UTC, closed without merging